### ISSUE TITLE
How do i run this project

### ISSUE THREAD

**Issue by schandrakandi** [chatch/stellar-contracts#2]
IS there any documentation which will help me to run this code on my machine
I tried to run but getting this error 

CleanImage-mb:stellar-contracts schandrakandi$ node src/App.js 
/Users/schandrakandi/stellar-contracts/src/App.js:1
(function (exports, require, module, __filename, __dirname) { import React, {Component} from 'react'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by chatch** [comment]
@schandrakandi i've just added the steps here: https://github.com/chatch/stellar-contracts#get-started

that will serve it @ http://localhost:3000

**Comment by schandrakandi** [comment]
Thanks, it works.
